import json
import numpy as np
import cv2
import os

CALIB_SAMPLES = "calibration_samples.json"
OUT_PY = os.path.join("common", "tool_cam_config.py")


def load_samples(path=CALIB_SAMPLES):
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"'{path}' not found. Run robot.apriltag_calibration first "
            "to collect calibration samples."
        )

    with open(path, "r") as f:
        samples = json.load(f)

    if not isinstance(samples, list) or len(samples) < 3:
        raise RuntimeError(
            f"Need at least 3 samples for hand–eye calibration, got {len(samples)}."
        )

    R_gripper2base = []  
    t_gripper2base = [] 
    R_target2cam = []   
    t_target2cam = []  

    for i, s in enumerate(samples):
        try:
            R_b_t = np.array(s["R_base_tool"], dtype=float)
            t_b_t = np.array(s["t_base_tool"], dtype=float)
            R_c_tag = np.array(s["R_cam_tag"], dtype=float)
            t_c_tag = np.array(s["t_cam_tag"], dtype=float)

            assert R_b_t.shape == (3, 3)
            assert R_c_tag.shape == (3, 3)
            assert t_b_t.shape == (3,)
            assert t_c_tag.shape == (3,)
        except Exception as e:
            raise RuntimeError(f"Bad sample format at index {i}: {e}")

        R_gripper2base.append(R_b_t)
        t_gripper2base.append(t_b_t)
        R_target2cam.append(R_c_tag)
        t_target2cam.append(t_c_tag)

    return (
        R_gripper2base,
        t_gripper2base,
        R_target2cam,
        t_target2cam,
    )


def solve_tool_cam():
    (
        R_gripper2base,
        t_gripper2base,
        R_target2cam,
        t_target2cam,
    ) = load_samples()

    R_cam2gripper, t_cam2gripper = cv2.calibrateHandEye(
        R_gripper2base,
        t_gripper2base,
        R_target2cam,
        t_target2cam,
        method=cv2.CALIB_HAND_EYE_TSAI,
    )


    R_cam2gripper = np.asarray(R_cam2gripper, dtype=float).reshape(3, 3)
    t_cam2gripper = np.asarray(t_cam2gripper, dtype=float).reshape(3)

    R_tool_cam = R_cam2gripper.T
    t_tool_cam = -R_tool_cam @ t_cam2gripper

    print("====== Hand-Eye Result (Tool→Cam) ======")
    print("R_tool_cam =")
    print(R_tool_cam)
    print("\nt_tool_cam =")
    print(t_tool_cam)

    os.makedirs(os.path.dirname(OUT_PY), exist_ok=True)

    with open(OUT_PY, "w") as f:
        f.write("# common/tool_cam_config.py\n")
        f.write("# Auto-generated by tools/solve_tool_cam.py\n")
        f.write("import numpy as np\n\n")
        f.write("R_tool_cam = np.array([\n")
        for row in R_tool_cam:
            f.write(f"    [{row[0]:.16f}, {row[1]:.16f}, {row[2]:.16f}],\n")
        f.write("])\n\n")
        f.write("t_tool_cam = np.array([\n")
        f.write(f"    {t_tool_cam[0]:.16f},\n")
        f.write(f"    {t_tool_cam[1]:.16f},\n")
        f.write(f"    {t_tool_cam[2]:.16f},\n")
        f.write("])\n")

    print(f"\n[✓] Saved Tool→Cam transform to {OUT_PY}")


if __name__ == "__main__":
    solve_tool_cam()
